### ISSUE TITLE
Lack of dependencies

### ISSUE THREAD

**Issue by chen2010z** [bronter/wgpu-native-zig#1]
You seem to have missed three dependency packages on Windows
wgpu_window_x86_Release、wgpu_window_x86_64_Debug、wgpu_window_x86_64_Release

**Comment by bronter** [comment]
Ah yeah, I didn't notice the "show all 15 results" part at the end of the asset list. It did seem strange that windows wouldn't have x86_64 releases...
Anyways, I've added the x86_64 windows target to the whitelist and added all three missing dependencies to build.zig.zon.
