### ISSUE TITLE
Build.zig dependency matching error

### ISSUE THREAD

**Issue by chen2010z** [bronter/wgpu-native-zig#3]
//Forgive me for using translation software to translate from Chinese to English
thread 27944 panic: no dependency named 'wgpu_windows_x86_64_ReleaseFast'

in build.zig at line 50: const mode_str = @tagName(optimize);
When I use release mode, the tagname for optimize is actually ReleaseFast/ReleaseSmall/ReleaseSafe
const mode_str = if (@intFromEnum(optimize) > 0) "Release" else "Debug"; //It is an optional solution

**Comment by bronter** [comment]
> //Forgive me for using translation software to translate from Chinese to English

No worries, it seems to be working pretty well.

> in build.zig at line 50: const mode_str = @TagName(optimize); When I use release mode, the tagname for optimize is actually ReleaseFast/ReleaseSmall/ReleaseSafe const mode_str = if (@intFromEnum(optimize) > 0) "Release" else "Debug"; //It is an optional solution

I should have tested in Release mode, for some reason I thought the enum only had Debug and Release.  I have updated it so that any mode other than Debug maps to "release", and have updated the dependency names accordingly.
